---
#- debug:
#    msg: "Configure {{ icinga2_feature_name }} when {{ ic2_f_options[icinga2_feature_name] }} is defined"
#  when: ic2_f_options[icinga2_feature_name]
#  tags:
#    - config
#    - feature
#    - debug

- name: "configure feature {{ icinga2_feature_name }}"
  template:
    dest: /etc/icinga2/features-available/{{ icinga2_feature_name }}.conf
    src: templates/generic_feature_template.j2
  when: ic2_f_options[icinga2_feature_name]
  notify: Test config before restart icinga 2
  tags:
    - feature

- name: "Enable icinga2 feature {{icinga2_feature_name}} - {{ icinga2_feature_name in icinga2_features }}"
  file:
    src: "../features-available/{{icinga2_feature_name}}.conf"
    dest: "/etc/icinga2/features-enabled/{{icinga2_feature_name}}.conf"
    owner: "{{icinga2_user[ansible_os_family]}}"
    group: "{{icinga2_user[ansible_os_family]}}"
    state: "{{'link' if ( icinga2_feature_name in icinga2_features ) else 'absent' }}"
  notify: Test config before restart icinga 2
  tags:
    - config
    - feature
    - feature_switch
